name: Build and publish dev-release Java distributions to sonatype.

on:
  workflow_dispatch:
  push:
    tags:
      - \d+.\d+.\d+-dev

jobs:
  build-job:
    uses: th2-net/.github/.github/workflows/compound-java.yml@main
    with:
      build-target: 'Docker'
      docker-username: ${{ github.actor }}
      devRelease: true
    secrets:
      docker-password: ${{ secrets.GITHUB_TOKEN }}